---
- name: Setup arch 
  hosts: all
  become: yes

  tasks:

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install noisetorch using yay
      kewlfft.aur.aur:
        use: yay
        name:
          - noisetorch-bin
      become: yes
      become_user: aur_builder

    - name: install bunch of packages
      pacman:
        update_cache: yes
        name:
          - zsh # Sure
          - yay # Yes
          - brightnessctl # The default one just doesn't work
          - tmux # Yup
          - bob # Manages neovim versions
          - obs-studio # I sometimes like to record stuff
          - htop # I usually open this when I'm doing java
          - ripgrep # To use with neovim
          - arandr # For using multiple monitors
          - picom
          - flameshot # Best screenshotting tool ever tbh
          - thefuck
          - go


    - name: install tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/nikanzeyaei/.tmux/plugins/tpl
        clone: yes
        update: yes

    - name: Clone neovim config 
      git:
        repo: https://github.com/NikanZeyaei/init.lua.git
        dest: /home/nikanzeyaei/.config/nvim
        clone: yes
        update: yes

    - include_tasks: docker.yml
    - include_tasks: zsh.yml
      
